site_name: Лабораторные работы по Web-программированию
nav:
  - Лабораторная работа №1:
      - Главная: index.md
      - Задание 1: task1.md
      - Задание 2: task2.md
      - Задание 3: task3.md
      - Задание 4: task4.md
      - Задание 5: task5.md
  - Лабораторная работа №2: lab2.md

theme:
  name: material
  language: ru
